[package]
name = "swerve_model"
version = "0.1.0"
edition = "2021"
authors = ["Patrick van der Velde"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
